### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by TwinMist** [info-beamer/package-stream-test#1]
Is is possible this plug-in can support youtube video urls?
many thanks

**Comment by dividuum** [comment]
No. Unless you provide it with the HLS url of the stream. You can try out https://info-beamer.com/pkg/6915 for streaming from youtube/twitch/etc.

**Comment by TwinMist** [comment]
For anyone wanting to stream Youtube looks like you need to use the embeaded url.
ie
https://www.youtube.com/embed/XOacA3RYrXk

**Comment by dividuum** [comment]
Those should work as well, but the usual `/watch?v=` urls work too.
